rest/slurmrestapi.py
Hello,
This pull request brings a new endpoint in the slurm rest api. This endpoint simply returns data in a similar format of sinfo.
3 files are touched:
rest/slurmrestapi.py which contains the endpoint definition
rest/utils.py which contains 2 methods to manipulate nodelist
tests/unit/test_utils.py which contains unit tests for rest/utils.py.
Unit test can be run using 
PYTHONPATH=$PYTHONPATH:. python tests/units/test_utils.py
Cheers,
Alex
=> Adding sinfo endpoint to slurmrestapi

docker/container/munge.sh
=> Force munged to suppress bound to socket error #168

CHANGELOG.md, conf/vendor/agent.yml, docs/modules/conf/partials/conf-agent.adoc, frontend/src/composables/GatewayAPI.ts, frontend/src/views/JobsView.vue
=> Display requested resources in jobs list

CHANGELOG.md, pyproject.toml, slurmweb/asyncrun.py, slurmweb/views/gateway.py
With aiohttp, retrieve clusters stats and permissions in parallel.
fix #304
=> feat(gateway): asynchronous clusters list

CHANGELOG.md, conf/vendor/gateway.yml, docs/modules/conf/examples/gateway.ini, docs/modules/conf/partials/conf-gateway.adoc, slurmweb/views/gateway.py
=> Possibility to hide denied clusters

CHANGELOG.md, conf/vendor/gateway.yml, docs/modules/conf/examples/gateway.ini, docs/modules/conf/partials/conf-gateway.adoc, pyproject.toml, slurmweb/apps/gateway.py, slurmweb/apps/ldap.py
=> Support custom user primary group attribute and group object classes

CHANGELOG.md, frontend/src/components/jobs/JobProgressComment.vue, frontend/tests/components/jobs/JobProgressComment.spec.ts
=> Display time limit of running jobs in jobs details page

frontend/tests/views/QosView.spec.ts
=> tests(front): cover QosView

frontend/src/composables/TimeDuration.ts, frontend/src/views/ReservationsView.vue, frontend/tests/composables/TimeDurations.spec.ts, frontend/tests/views/ReservationsView.spec.ts
=> tests(front): cover ReservationsView

CHANGELOG.md, frontend/src/components/jobs/JobsSorter.vue, frontend/src/composables/GatewayAPI.ts, frontend/src/stores/runtime.ts, frontend/src/views/JobsView.vue, frontend/tests/composables/GatewayAPI.spec.ts
=> Sort jobs by resources

CHANGELOG.md, frontend/src/views/JobsView.vue
Replace view job link by a window icon in jobs list.
=> refactor(front): job view link replaced by icon

CHANGELOG.md, frontend/src/views/JobsView.vue, frontend/tests/views/JobsView.spec.ts
=> Add priority column in jobs list

.github/workflows/ci.yml
Add OS integration tests by running unit tests on all supported OS distributions.
fix #518
=> chore(ci): add OS integration tests

CHANGELOG.md, slurmweb/metrics/collector.py
Fix AttributeError with prometheus_client.registry.Collector with prometheus_client < 0.14.0 available on el8.
fix #548
=> fix(agent): prometheus collector error on el8

slurmweb/tests/slurmrestd/test_slurmrestd.py
=> tests(agent): fix syntax warning invalid sequence

CHANGELOG.md, frontend/public/config.json, frontend/src/components/MainMenu.vue, frontend/src/plugins/runtimeConfiguration.ts, slurmweb/tests/views/test_gateway.py, slurmweb/views/gateway.py
=> Display version in UI main menu

slurmweb/tests/lib/utils.py, slurmweb/tests/views/test_gateway.py, slurmweb/tests/views/test_gateway_clusters.py
=> Add unit tests to cover gateway /clusters

CHANGELOG.md, conf/vendor/gateway.yml, dev/crawler/agent.py, docs/modules/conf/examples/gateway.ini, docs/modules/conf/partials/conf-gateway.adoc, slurmweb/apps/agent.py, slurmweb/apps/gateway.py, slurmweb/tests/apps/test_gateway.py, slurmweb/tests/lib/gateway.py, slurmweb/tests/views/test_agent.py, slurmweb/tests/views/test_gateway_clusters.py, slurmweb/tests/views/test_gateway_permissions.py, slurmweb/views/agent.py, tests/assets/agent/info.json
=> Generic agent info endpoint

CHANGELOG.md, pyproject.toml, slurmweb/apps/gateway.py, slurmweb/tests/apps/test_gateway.py, slurmweb/tests/lib/utils.py, slurmweb/views/gateway.py
=> Use aiohttp in gateway to discover agents

CHANGELOG.md, conf/vendor/gateway.yml, docs/modules/conf/examples/gateway.ini, docs/modules/conf/partials/conf-gateway.adoc, slurmweb/apps/__init__.py, slurmweb/apps/gateway.py, slurmweb/apps/ldap.py, slurmweb/tests/apps/test_load_ldap_password_from_file.py
Closes https://github.com/rackslab/Slurm-web/issues/585.
=> feat(gateway): Allow ldap bind password to be read from file

CHANGELOG.md, slurmweb/cache.py, slurmweb/tests/test_cache.py
=> Fix crash in metrics on missing cache keys
