rackslab/Slurm-web

- doc/installation.rst
- docker/container/Dockerfile
- docker/container/apache2.sh
- docker/container/munge.sh
- docker/run/run.sh
This PR provides:
* a Dockerfile to build and deploy Slurm-web as a container
* a runscript to run the container
* instructions to build and run the container.
> Add Docker support

- debian/changelog
Incorrect abbreviation of month (August) was causing issues in debuild.
> Fixed month abbreviation in debian/changelog

- CHANGELOG.md
- frontend/src/components/jobs/JobsFiltersPanel.vue
- slurmweb/apps/__init__.py
- slurmweb/views/gateway.py
Hide users disclosure from jobs filters panel and report JSON error with HTTP/501 when requesting users list.
fix #330
> Hide users jobs filters when authentication is disabled

- CHANGELOG.md
- conf/vendor/agent.yml
- docs/modules/conf/examples/agent.ini
- docs/modules/conf/partials/conf-agent.adoc
- frontend/src/composables/GatewayAPI.ts
- frontend/src/views/ClustersView.vue
- frontend/src/views/DashboardView.vue
- slurmweb/views/agent.py
> Display slurm version in clusters list

- CHANGELOG.md
- slurmweb/views/agent.py
Also log clear error message to mention unsupported Slurm version.
fix #316
> Avoid KeyError with warnings on old unsupported Slurm version

- CHANGELOG.md
- conf/vendor/agent.yml
- dev/conf/agent.ini.j2
- dev/setup-dev-environment
- docs/modules/conf/examples/agent.ini
- docs/modules/conf/partials/conf-agent.adoc
- frontend/src/components/resources/ResourcesCanvas.vue
- frontend/src/composables/GatewayAPI.ts
- slurmweb/apps/agent.py
- slurmweb/apps/gateway.py
- slurmweb/views/agent.py
- slurmweb/views/gateway.py
> Support custom RacksDB infrastructure name

- slurmweb/apps/agent.py
- slurmweb/errors.py
- slurmweb/slurmrestd/__init__.py
- slurmweb/slurmrestd/errors.py
- slurmweb/slurmrestd/unix.py
- slurmweb/tests/test_agent.py
- slurmweb/tests/test_slurmrestd.py
- slurmweb/tests/utils.py
- slurmweb/views/__init__.py
- slurmweb/views/agent.py
Introduce `Slurmrestd` class, with `SlurmrestdFiltered` and `SlurmrestdFilteredCached` to manage respectively interface with `slurmrestd`, keys filtering and cache layer.
> Refactor slurmrestd interface in agent

- CHANGELOG.md
- slurmweb/apps/gateway.py
- slurmweb/errors.py
- slurmweb/tests/assets/agent/info.json
- slurmweb/tests/metrics/test_db.py
- slurmweb/tests/test_agent.py
- slurmweb/tests/test_gateway.py
- slurmweb/tests/utils.py
> Fix `AttributeError` on `requests.exception.JSONDecodeError`

- CHANGELOG.md
- slurmweb/apps/gateway.py
- slurmweb/tests/test_gateway.py
It is not only about the name of the cluster.
> Change agent info fields parsing error message to reflect new response content

- CHANGELOG.md
- frontend/src/components/job/JobFieldComment.vue
- frontend/src/components/job/JobFieldExitCode.vue
- frontend/src/components/job/JobFieldRaw.vue
- frontend/src/components/job/JobFieldTRES.vue
- frontend/src/composables/GatewayAPI.ts
- frontend/src/views/JobView.vue
- frontend/tests/views/JobView.spec.ts
- frontend/tests/views/common.ts
> Anchors to highlight job fields

- slurmweb/tests/views/test_agent.py
Since RFL v1.2.0, authenticated users do not inherit anonymous role by default anymore.
> tests(agent): authd users w/o anonymous role

- .github/workflows/ci.yml
- CHANGELOG.md
- slurmweb/apps/agent.py
- slurmweb/tests/lib/agent.py
- slurmweb/tests/lib/utils.py
- slurmweb/tests/views/test_agent.py
- slurmweb/tests/views/test_gateway.py
This PR tracks the work to fix #419.
> Fix ModuleNotFoundError: No module named 'werkzeug.middleware' on el8

- CHANGELOG.md
- frontend/vite.config.ts
Reduce size of JS chunk by moving chart.js and luxon libraries in separate vendor chunk.
fix #414
> fix(front): split JS chunk

- .github/workflows/ci.yml
During some runs, apt-get install fails on 404 due to packages not found in remote ubuntu repositories. This is generally due to out-of-date repository metadata and is fixed by a simple update.
> chore(ci): run apt update before install

- CHANGELOG.md
- frontend/src/components/resources/ResourcesCanvas.vue
Remove workaround for Firefox to avoid blurry lines in racks canvas, fixed in Firefox ESR >= 128 and Firefox >= 133. For reference, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1847681
> refactor(front): remove firefox blurry workaround

- CHANGELOG.md
- frontend/package-lock.json
- frontend/package.json
Fix the following security issue:
vite  <=4.5.5 || 5.0.0 - 5.4.11
Severity: moderate
Websites were able to send any requests to the development server and
read the response in vite -
https://github.com/advisories/GHSA-vg6x-rcgg-rjx6
> fix(front): npm audit fix vite

- CHANGELOG.md
- slurmweb/apps/agent.py
- slurmweb/tests/apps/test_agent.py
- slurmweb/tests/lib/agent.py
- slurmweb/tests/views/test_agent_racksdb.py
> Report error instead of failing when RacksDB unable to load database

- CHANGELOG.md
- frontend/src/components/ClustersPopOver.vue
- frontend/src/components/clusters/ClustersListItem.vue
- frontend/src/composables/GatewayAPI.ts
- frontend/src/stores/runtime.ts
- frontend/src/views/ClustersView.vue
- frontend/tests/components/clusters/ClustersListItem.spec.ts
- frontend/tests/views/ClustersView.spec.ts
- slurmweb/views/gateway.py
Some tasks are still pending:
fix #428
> Asynchronous requests to retrieve stats in clusters list

- CHANGELOG.md
- docs/modules/conf/partials/uwsgi-services-http.adoc
- docs/modules/conf/partials/uwsgi-services.adoc
Fix cp command to copy examples of uWSGI services provided in Slurm-web packages.
fix #448
> docs: fix cp uwsgi services command

- CHANGELOG.md
- conf/vendor/gateway.yml
- docs/modules/conf/examples/gateway.ini
- docs/modules/conf/partials/conf-gateway.adoc
- slurmweb/apps/gateway.py
> Search for user DN in the scope of LDAP user base before authentication

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Add initial version of issue templates in order to restrict issues to actual bugs and feature requests, and route questions to Q&A section of GitHub discussions.
> chore: add github issue templates

- CHANGELOG.md
- frontend/src/composables/GatewayAPI.ts
Add missing bearer token in RacksDB infrastructure diagram request, it is now required by @check_jwt decorator on the gateway endpoint with RFL >= 1.3.0 to avoid HTTP/403 response.
The token is removed from request headers for login (incl. anonymous) and login service message at the same time, as the client does not have JWT at this stage yet and the gateway does not enforce the presence of the bearer token for the corresponding endpoints.
fix #471
> fix(front): add bearer token in racksdb request

- .github/workflows/ci.yml
New version of PyGObject 3.52.1 (RacksDB dependency) depends on libgirepository-2.0-dev on ubuntu-latest, then install it in build environment.
> chore(ci): add system dep for PyGObject

- CHANGELOG.md
- frontend/package-lock.json
- frontend/package.json
Fix the following security issues in dependencies:
axios  <1.8.2
Severity: high
axios Requests Vulnerable To Possible SSRF and Credential Leakage via
Absolute URL - https://github.com/advisories/GHSA-jr5f-v2jv-69x6
cross-spawn  <6.0.6 || >=7.0.0 <7.0.5
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn -
https://github.com/advisories/GHSA-3xgq-45jj-v275
esbuild  <=0.24.2
Severity: moderate
esbuild enables any website to send any requests to the development
server and read the response -
https://github.com/advisories/GHSA-67mh-4wv8-2f99
nanoid  <3.3.8
Severity: moderate
Predictable results in nanoid generation when given non-integer
values - https://github.com/advisories/GHSA-mwcw-c2x4-8c55
rollup  3.0.0 - 3.29.4 || 4.0.0 - 4.22.3
Severity: high
DOM Clobbering …
> fix(front): npm audit fix --force

- CHANGELOG.md
- slurmweb/version.py
Use standard library importlib.metadata to retrieve package version instead of using setuptools pkg_resources which raises DeprecationWarning 'pkg_resources is deprecated as an API' with setuptools >= 67.
Unfortunately, importlib.metadata is only available starting with Python 3.8. On older versions of Python, importlib_metadata backport external library is used, which adds new dependency on these old versions of Python.
> fix: deprecation warning on pkg_resources

- CHANGELOG.md
- slurmweb/apps/gateway.py
Add support of strings parts in RacksDB and agent version comparison logic.
> fix(gateway): support str in version comparison

- .github/workflows/ci.yml
This error now raises on Python 3.6:
error: pyasn1 0.5.1 is installed but pyasn1<0.7.0,>=0.6.1 is required
by {'pyasn1-modules'}
The pyasn1 dependency is due to python-ldap. Try to fix it by installing an older version of python-ldap, similarly to el8.
> chore(ci): fix pyasn1 dep error on python 3.6

- CHANGELOG.md
- frontend/src/composables/DataGetter.ts
- frontend/src/composables/DataPoller.ts
- frontend/src/composables/HTTPErrors.ts
- frontend/src/composables/RESTAPI.ts
Do not display canceled requests errors to end users, they are expected and add no value for users.
fix #507
> refactor(front): ignore canceled requests errors

- .github/workflows/ci.yml
GitHub Actions dropped support of ubuntu-20.04 runners, there is no obvious solution anymore to setup python 3.6. Tests on this environment are disabled until a durable solution is found.
> chore(ci): disable py3.6 tests on ubuntu-20.04

- CHANGELOG.md
- conf/vendor/gateway.yml
- docs/modules/conf/examples/gateway.ini
- docs/modules/conf/partials/conf-gateway.adoc
- frontend/public/config.json
- frontend/src/composables/GatewayAPI.ts
- frontend/src/plugins/runtimeConfiguration.ts
- slurmweb/tests/views/test_gateway.py
- slurmweb/views/gateway.py
> Disable racks and rows labels by default in clusters graphical representations

- frontend/src/components/ClusterMainLayout.vue
- frontend/src/components/MainMenu.vue
- frontend/src/router/index.ts
- frontend/src/stores/runtime.ts
- frontend/src/views/DashboardView.vue
- frontend/src/views/JobView.vue
- frontend/src/views/JobsView.vue
- frontend/src/views/NodeView.vue
- frontend/src/views/QosView.vue
- frontend/src/views/ReservationsView.vue
- frontend/src/views/ResourcesView.vue
Simply use a prop to control main meny entry instead of a route meta checked by route guard to fill runtime store.
> refactor(front): main menu entry as prop

- frontend/src/views/JobsView.vue
The max-w-fit class in last cell td was causing spurious horizontal scroll bar for just a few empty pixels. It is removed and icon is right aligned thanks to inline-block.
> fix(front): spurious horizontal scroll with jobs

- frontend/src/composables/Nodeset.ts
Fix TS7034 error: Variable 'node_ids' implicitly has type 'any[]' in some locations where its type cannot be determined.
> refactor(front): fix implicit any

- lib/wsgi/agent/slurm-web-agent.py
- lib/wsgi/gateway/slurm-web-gateway.py
Add missing SlurmwebConfSeed log_component argument in WSGI scripts. Regression introduced with 6100516.
> fix(lib): missing conf seed log_component argument

- .github/workflows/ci.yml
- pyproject.toml
- slurmweb/tests/lib/agent.py
- slurmweb/tests/lib/slurmrestd.py
- slurmweb/tests/lib/utils.py
- slurmweb/tests/slurmrestd/test_slurmrestd.py
- slurmweb/tests/slurmrestd/test_slurmrestd_filtered.py
- slurmweb/tests/slurmrestd/test_slurmrestd_filtered_cached.py
- slurmweb/tests/views/test_agent.py
- slurmweb/tests/views/test_agent_metrics_collector.py
The initial plan was to use pytest parametized but it does not support decorators on unittest.TestCase methods. It is mentioned in pytest documentation: https://docs.pytest.org/en/stable/how-to/unittest.html#pytest-features-in-unittest-testcase-subclasses
The alternative is to use parameterized external library, just as we do in RacksDB.
fix #540
> Use parameterized to test all versions of Slurm

- CHANGELOG.md
- docs/antora.yml
- docs/modules/install/pages/quickstart.adoc
- docs/modules/overview/pages/architecture.adoc
Bump main Slurm-web version and REST API version in docs metadata. Mention support added of Slurm 25.05 and removed for Slurm 23.11. Also mention minimum Slurm version is now 24.05.
> docs: bump API version and support Slurm 25.05

- CHANGELOG.md
- dev/crawler/gateway.py
- dev/crawler/lib.py
- dev/crawler/slurmrestd.py
- frontend/src/composables/GatewayAPI.ts
- frontend/tests/composables/GatewayAPI.spec.ts
- tests/assets/gateway/node-with-gpus-allocated.json
- tests/assets/gateway/node-with-gpus-mixed.json
- tests/assets/gateway/node-with-gpus-model-allocated.json
- tests/assets/gateway/node-with-gpus-model-idle.json
- tests/assets/gateway/node-with-gpus-model-mixed.json
- tests/assets/gateway/status.json
- tests/assets/slurmrestd/24.11/slurm-node-with-gpus-allocated.json
- tests/assets/slurmrestd/24.11/slurm-node-with-gpus-mixed.json
- tests/assets/slurmrestd/24.11/slurm-node-with-gpus-model-allocated.json
- tests/assets/slurmrestd/24.11/slurm-node-with-gpus-model-idle.json
- tests/assets/slurmrestd/24.11/slurm-node-with-gpus-model-mixed.json
- tests/assets/slurmrestd/24.11/status.json
- tests/assets/slurmrestd/25.05/slurm-node-with-gpus-model-allocated.json
- tests/assets/slurmrestd/25.05/slurm-node-with-gpus-model-idle.json
- tests/assets/slurmrestd/25.05/slurm-node-with-gpus-model-mixed.json
- tests/assets/slurmrestd/25.05/status.json
This moves to a regular expression matcher rather than just splitting on `:` and assuming the number of fields. This will pull out a model if it exists and a count (assumed to exist because it's a hard requirement). The regular expression utilizes lookback assertions on the `:` character to make sure the capture groups do not include the `:` character. It simply extracts the model (if exists) and count.
I have tested this locally with an active Slurm deployment that has both GPUs with models known and models unknown and they render correctly. In the case of unknown models, we simply say "unknown".
EDIT: The new commit makes sure to remove the unnecessary `IDX` information before parsing the GPU information from the string.
Closes #584
> fix(front): properly handle the case where GPU model is unknown in gres

- CHANGELOG.md
- frontend/src/composables/GatewayAPI.ts
- frontend/tests/composables/GatewayAPI.spec.ts
We met an error where one of our nodes has no GPUs in Slurm-Web.
After the investigation, I was able to localize the error and fix it. It was caused by the weird Socket IDs in the DGX A100 server.
The previous version of the code was splitting the gres string by all comma characters; the suggested version splits only by commas, if they are not enclosed in brackets.
> fix: unable to parse GPUs from GRES if there is a comma in brackets

- CHANGELOG.md
- docs/modules/conf/partials/conf-gateway.adoc
- docs/utils/conf-ref.adoc.j2
Fix rendering of example list values in generated configuration reference documentation.
fix #599
> docs: fix rendering of example list params

- slurmweb/apps/__init__.py
Potential fix for [https://github.com/rackslab/Slurm-web/security/code-scanning/1](https://github.com/rackslab/Slurm-web/security/code-scanning/1)
To fix the issue, the logging statement should be modified to avoid including sensitive information such as the file path. Instead, a generic message can be logged to indicate the operation without revealing specifics. This ensures that no sensitive data is exposed in the logs.
The fix involves:
1. Replacing the logging statement on line 33 with a generic message that does not include the file path.
2. Ensuring that the functionality of the code remains unchanged while improving security.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 1: Clear-text logging of sensitive information
